- src/libs/planner.js
> Planner system!

- src/libs/blockSchedule.js
- src/libs/schedule.js
- src/schedules/highschool.json
This pull request fixes issue #29 by adding the actual free period instead of just prefixing lunch with "Block X +"
> Schedule fix

- API Endpoints.md
- src/index.js
- src/libs/canvas.js
- src/libs/feeds.js
- src/libs/portal.js
- src/libs/schedule.js
- src/libs/weather.js
- src/routes/canvasAPI.js
- src/routes/feedsAPI.js
- src/tasks.js
> Feed caching

- src/libs/canvas.js
Fixes https://github.com/MyMICDS/MyMICDS-v2-Angular/issues/39
> Re-add `canvas: true` so front-end can distinguish from other events

- src/libs/aliases.js
- src/libs/classes.js
- src/libs/planner.js
- src/libs/teachers.js
This PR refactors some of the more complicated logic inside various class and schedule functions to use Mongo aggregations instead of pure JS and many consecutive database queries. Addresses #67.
> Aggregations

- src/libs/config.example.js
- src/libs/portal.js
- src/libs/schedule.js
This PR changes some functions to do with Portal and schedule parsing to migrate from the old portal to the new Veracross system.
> Switch from Portal to Veracross

- src/libs/feeds.js
- src/libs/portal.js
- src/libs/schedule.js
- src/libs/users.js
- src/routes/feedsAPI.js
- src/routes/portalAPI.js
- src/tasks.js
- Add additional 'My Calendar' input
While this second feed doesn't do anything at the moment, it may have some useful data such as assemblies, sports practices, etc.
> Finalize Veracross Integration

- src/libs/schedule.js
- Also pull global calendar for detecting special schedule
> Fix special schedule detection

- src/libs/schedule.js
> Only special schedule on date if special schedule is on date

- src/libs/schedule.js
This is for things like assembly
> Overlay school-wide events/classes on personal schedule

- src/libs/dates.ts
> Bugs on promisify

- src/libs/jwt.ts
- src/libs/modules.ts
- src/routes/backgroundAPI.ts
- src/routes/modulesAPI.ts
- src/routes/plannerAPI.ts
This PR fixes some issues with Express and an issue regarding module type validation.
> General bugfixes

- package-lock.json
- package.json
- src/index.ts
- src/init.ts
- src/libs/api.ts
This PR adds Sentry integration for any unexpected backend errors. Resolves #139.
> Sentry error logging

- package-lock.json
- package.json
- src/libs/auth.ts
- src/libs/blockSchedule.ts
- src/libs/canvas.ts
- src/libs/dailyBulletin.ts
- src/libs/feeds.ts
- src/libs/jwt.ts
- src/libs/modules.ts
- src/libs/portal.ts
- src/libs/schedule.ts
- src/libs/users.ts
- test/auth.test.ts
- test/classes.test.ts
- test/feeds.test.ts
- test/helpers/shared.ts
- test/modules.test.ts
- test/planner.test.ts
- test/portal.test.ts
- test/stickynotes.test.ts
- test/user.test.ts
This PR removes Underscore and replaces it with native JavaScript functionality and Lodash. Closes #91.
> Replace Underscore with Lodash

- package-lock.json
- package.json
- src/init.ts
- src/libs/api.ts
- src/scripts/newsletter.ts
- tsconfig.json
Implements optional chaining for slightly cleaner code.
> ES2020 + mini-refactor w/ optional chaining

- src/libs/canvas.ts
- test/calendars/canvasWithCalEvents.ics
- test/canvas.test.ts
Resolves #150. Includes two new tests to make sure calendar events are functional.
> Re-enable Canvas calendar events

- package-lock.json
- package.json
- test/auth.test.ts
This PR fixes a bug that was emailed in where a teacher couldn't sign up because `null` wasn't handled for the `gradYear` field.
> Fix teacher signups

- package-lock.json
- src/libs/portal.ts
This PR should resolve a bunch of Sentry errors we've been seeing with people inputting the wrong URLs, which shouldn't be giving 500 errors.
> Fix invalid URL errors

- .github/workflows/workflow.yml
This PR adds Sentry commit tracking, which should allow for better diagnostic information within Sentry events.
> Add Sentry commit-tracking

- .eslintrc.json
- src/libs/admins.ts
- src/libs/aliases.ts
- src/libs/api.ts
- src/libs/auth.ts
- src/libs/backgrounds.ts
- src/libs/canvas.ts
- src/libs/checkedEvents.ts
- src/libs/classes.ts
- src/libs/cryptoUtils.ts
- src/libs/dailyBulletin.ts
- src/libs/errors.ts
- src/libs/feeds.ts
- src/libs/googleServiceAccount.ts
- src/libs/jwt.ts
- src/libs/lunch.ts
- src/libs/mail.ts
- src/libs/notifications.ts
- src/libs/passwords.ts
- src/libs/planner.ts
- src/libs/portal.ts
- src/libs/quotes.ts
- src/libs/snowdayCalculator.ts
- src/libs/stats.ts
- src/libs/teachers.ts
- src/libs/users.ts
- src/libs/weather.ts
> Wrap internal errors

- src/libs/lunch.ts
This PR should take care of the Sentry issue we've been seeing with lunch.
> Lunch hotfix

- package-lock.json
- package.json
- src/libs/canvas.ts
- src/libs/portal.ts
- src/libs/snowdayCalculator.ts
> remove em'
